[package]
name = "dispatcher-crate"
version.workspace = true
edition.workspace = true

[lib]
name = "dispatcher"
crate-type = ["cdylib", "rlib"]

[dependencies]
neural-core = { path = "../neural_core" }
llama = { path = "../llama" }

system-optimization = { path = "../../inference-engine/engines/system_optimization" }
libloading = "0.8"
engine-core = { path = "../../inference-engine/engines/core" }
anyhow = "1.0"
async-trait = "0.1"
tracing = "0.1"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
