[workspace]
members = [
    "inference-engine/api",
    "inference-engine/engines",
    "inference-engine/engines/core",
    "inference-engine/engines/system_optimization",
    "cmd",
    "tools/cluaiz-builder",
    "test/dummy_plugin",
    "developer_hub",
    "interface-engines/llama",
    "interface-engines/onnx",
    "interface-engines/dispatcher"
, "inference-cel", "test/plugin_testing", "test/engine_cel_test", "test/ai_search_e2e_test", "test/comprehensive_e2e_trace", "test/integration"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Cluaiz Technologies"]

[profile.dev]
debug = false
split-debuginfo = "off"
