[package]
name = "cluaiz_api"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
engines = { path = "../engines" }
dispatcher = { path = "../../interface-engines/dispatcher", package = "dispatcher-crate" }
system-optimization = { path = "../engines/system_optimization" }
engine-core = { path = "../engines/core" }
inference-cel = { path = "../../inference-cel" }
cluaiz_devhub = { path = "../../developer_hub" }

# ── Web Server (The Gateway) ──
axum       = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
tokio      = { version = "1", features = ["full"] }

# ── Data Serialization ──
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"

# ── Logging & Terminal ──
tracing            = "0.1"
tracing-subscriber = "0.3"
colored            = "2.1"
sysinfo            = "0.33"
dirs = "5.0"
futures = "0.3"
async-stream = "0.3"
serde_yaml = "0.9.34"
reqwest = { version = "0.13.4", features = ["json"] }
uuid = { version = "1.24.0", features = ["v4"] }
base64 = "0.22.1"
eyre = "0.6.12"
